### ISSUE TITLE
Fix content previews

### ISSUE THREAD

**Issue by idosius** [wunderdogsw/w3#35]
Reproduction steps:

1. Open some content on Contentful, e.g. https://app.contentful.com/spaces/hkq76neqke2v/entries/2WjiX2XfEVoW2Fz6DlZaR7
2. Click Open preview on the right
3. You will get a 404 error

Toto recommends checking Netlify rather than Gatsby Cloud

**Comment by midori0507** [comment]
Currently we are using Gatsby Cloud for incremental build 
But seems like their Preview + Contentful are not really smooth, or lets say not as good as Netlify

I would recommend we get rid of Gatsby Cloud totally and move to Netlify

**Comment by idosius** [comment]
Fixed by @midori0507
